/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idevexpert.schoolnotes_fts3096_desktop.view.coordinator.additionalComponent;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Jesus Gutierrez
 */
public class ButtonStateAccountPerson extends javax.swing.JPanel {

    /**
     * Creates new form ButtonStateAccountPerson
     */
    public ButtonStateAccountPerson() {
        initComponents();
        actionButtonDesbloc.setFocusPainted(false);
        actionButtonBloc.setFocusPainted(false);
        actionButtonEdit.setFocusPainted(false);

    }

    public void initEvent(TableActionEvent event, int row) {
        actionButtonDesbloc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onAction(row, 1);
            }
        });
        actionButtonEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onAction(row, 2);
            }
        });
        actionButtonBloc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onAction(row, 3);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        actionButtonBloc = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton();
        actionButtonDesbloc = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton();
        actionButtonEdit = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setLayout(new java.awt.GridBagLayout());

        actionButtonBloc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -76;
        gridBagConstraints.ipady = -95;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 5, 0);
        add(actionButtonBloc, gridBagConstraints);

        actionButtonDesbloc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-slash.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -75;
        gridBagConstraints.ipady = -95;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 5, 0);
        add(actionButtonDesbloc, gridBagConstraints);

        actionButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -67;
        gridBagConstraints.ipady = -89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 5, 0);
        add(actionButtonEdit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton actionButtonBloc;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton actionButtonDesbloc;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ActionButton actionButtonEdit;
    // End of variables declaration//GEN-END:variables
}
