/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idevexpert.schoolnotes_fts3096_desktop.view.coordinator.additionalComponent;

import com.idevexpert.schoolnotes_fts3096_desktop.utlis.ColorUtil;

/**
 *
 * @author Jesus Gutierrez
 */
public class CreateAccountPerson extends javax.swing.JPanel {

    /**
     * Creates new form createAccountPerson
     */
    public CreateAccountPerson() {
        initComponents();
        textFieldUsuarName.setOpaque(false);
        
        passwordFieldAtributPassword.setOpaque(false);
        passwordFieldRepitPassword.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldUsuarName = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.TextField();
        passwordFieldAtributPassword = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField();
        passwordFieldRepitPassword = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        button1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.Button();
        imageAvatar1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar();

        textFieldUsuarName.setLabelText("USUARIO");

        passwordFieldAtributPassword.setLabelText("CONTRASEÑA");
        passwordFieldAtributPassword.setLineColor(new java.awt.Color(255, 102, 51));
        passwordFieldAtributPassword.setShowAndHide(true);

        passwordFieldRepitPassword.setLabelText("REPETIR CONTRASEÑA");
        passwordFieldRepitPassword.setLineColor(new java.awt.Color(255, 102, 51));
        passwordFieldRepitPassword.setShowAndHide(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Crear Cuenta");

        button1.setText("CREAR CUENTA");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_school_login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldUsuarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordFieldAtributPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordFieldRepitPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldUsuarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordFieldAtributPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordFieldRepitPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.Button button1;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField passwordFieldAtributPassword;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField passwordFieldRepitPassword;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.TextField textFieldUsuarName;
    // End of variables declaration//GEN-END:variables
}
