/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idevexpert.schoolnotes_fts3096_desktop.view.coordinator.additionalComponent;

import com.idevexpert.schoolnotes_fts3096_desktop.utlis.ColorUtil;

/**
 *
 * @author Jesus Gutierrez
 */
public class CreateAccountPerson extends javax.swing.JPanel {

    /**
     * Creates new form createAccountPerson
     */
    public CreateAccountPerson() {
        initComponents();
        textFieldUsuarName.setBackground(ColorUtil.kPrimaryTransparent);
        passwordFieldAtributPassword.setBackground(ColorUtil.kPrimaryTransparent);
        passwordFieldRepitPassword.setBackground(ColorUtil.kPrimaryTransparent);
        setBackground(ColorUtil.kPrimaryTransparent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.PanelRound();
        textFieldUsuarName = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.TextField();
        passwordFieldAtributPassword = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField();
        passwordFieldRepitPassword = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField();
        jLabel1 = new javax.swing.JLabel();
        button1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.Button();
        imageAvatar1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar();

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        textFieldUsuarName.setLabelText("USUARIO");

        passwordFieldAtributPassword.setLabelText("CONTRASEÑA");
        passwordFieldAtributPassword.setLineColor(new java.awt.Color(255, 102, 51));
        passwordFieldAtributPassword.setShowAndHide(true);

        passwordFieldRepitPassword.setLabelText("REPETIR CONTRASEÑA");
        passwordFieldRepitPassword.setLineColor(new java.awt.Color(255, 102, 51));
        passwordFieldRepitPassword.setShowAndHide(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Crear Cuenta");

        button1.setText("CREAR CUENTA");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_school_login.png"))); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldUsuarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordFieldAtributPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordFieldRepitPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldUsuarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordFieldAtributPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordFieldRepitPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.Button button1;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.PanelRound panelRound1;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField passwordFieldAtributPassword;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.PasswordField passwordFieldRepitPassword;
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.TextField textFieldUsuarName;
    // End of variables declaration//GEN-END:variables
}
