/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idevexpert.schoolnotes_fts3096_desktop.utlis;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import javax.swing.Timer;

/**
 *
 * @author Jesus Gutierrez
 */
public class LodingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form LodingJpanel
     */
    public LodingJpanel() {
        
        initComponents();
        setBackground(ColorUtil.kPrimaryTransparent);
        imageAvatar1.setBackground(ColorUtil.kPrimaryTransparent);
        //jLabel1.setBackground(ColorUtil.kPrimaryTransparent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imageAvatar1 = new com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar();

        setLayout(new java.awt.GridBagLayout());

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loadingPanel.gif"))); // NOI18N
        imageAvatar1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 203;
        gridBagConstraints.ipady = 202;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(186, 349, 185, 336);
        add(imageAvatar1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idevexpert.schoolnotes_fts3096_desktop.utlis.ImageAvatar imageAvatar1;
    // End of variables declaration//GEN-END:variables
}
